
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqkxhgnsqwvhukgvwjvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxa3hoZ25zcXd2aHVrZ3Z3anZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDI3NjIsImV4cCI6MjA2OTc3ODc2Mn0.o3Ch98U9nWIQaWcPViGZpcdQyHgGnJXSizVRR5YZ_JA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
