// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agikvjvzqmgjfymficjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnaWt2anZ6cW1namZ5bWZpY2ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODYxOTEsImV4cCI6MjA3MTY2MjE5MX0.0yCUCqwmwy76NDvrDj3d6_9ht7Ne-zKn1LbyMMUvnpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});