// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wziqvrtgswgsljqlaifn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6aXF2cnRnc3dnc2xqcWxhaWZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzNDQzMTUsImV4cCI6MjA4NzkyMDMxNX0.Q1E95Fuog_laHcIWdiU2spHdtEy4KEglZNCqYgdSmok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});